Add helm charts for vm-single, vmauth; Update prometheus values for r…
opentelekomcloud-infra/system-config pull request #1025
Opened 2024-04-23 10:36 UTC by Persimmonboy

…emote_write

2024-04-30 12:50 UTC, vladimirvshivkov requested changes

2024-04-30 12:50 UTC, vladimirvshivkov commented on kubernetes/helm/victoria-metrics-auth/values.yaml
> +# Default values for victoria-metrics-auth.
remove default values, please

2024-05-06 09:47 UTC, Persimmonboy commented on kubernetes/helm/victoria-metrics-auth/values.yaml
> +# Default values for victoria-metrics-auth.
Removed.

2024-05-06 09:49 UTC, vladimirvshivkov approved these changes

2024-05-06 12:21 UTC, vladimirvshivkov approved these changes

2024-05-06 12:35 UTC, merged