Cronjob eco issues
opentelekomcloud-infra/system-config pull request #980
Opened 2024-02-07 13:12 UTC by YustinaKvr

1) Del cronjobs for deleted scripts
2) Add cronjob for ecosystem_issues.py script
3) Fix kustomization.yaml

2024-02-08 08:21 UTC, vladimirvshivkov submitted a review, later dismissed

2024-02-09 11:03 UTC, vladimirvshivkov requested changes

2024-02-09 11:03 UTC, vladimirvshivkov commented on kubernetes/grafana-docs-monitoring/base/cronjob-ei.yaml
> +  name: grafana-docs-monitoring-failed-zuul
change failed zuul to eco-issues here

2024-02-09 11:03 UTC, vladimirvshivkov commented on kubernetes/grafana-docs-monitoring/base/cronjob-ei.yaml
> +            - name: grafana-docs-monitoring-failed-zuul
and here

2024-02-09 23:27 UTC, YustinaKvr commented on kubernetes/grafana-docs-monitoring/base/cronjob-ei.yaml
> +            - name: grafana-docs-monitoring-failed-zuul
fixed

2024-02-09 23:28 UTC, YustinaKvr commented on kubernetes/grafana-docs-monitoring/base/cronjob-ei.yaml
> +  name: grafana-docs-monitoring-failed-zuul
fixed

2024-02-12 09:28 UTC, vladimirvshivkov approved these changes

2024-02-12 10:18 UTC, merged